name: ci-prod

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false

      - name: Build & Push Prod Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pakvista:prod-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/pakvista:prod-${{ github.sha }}
